services:
  mysql:
    image: mysql:8.3
    container_name: dumbcatan-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: catanv2
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend: 
    image: ryanmatuszak/dumbcatanv2-server:latest
    container_name: springboot
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    image: ryanmatuszak/dumbcatanv2-client:latest
    container_name: react
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mysql-data: